# Generated by Django 5.0 on 2023-12-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0009_comments_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Movie_link',
            field=models.FileField(default='null.mp4', upload_to='movies'),
        ),
        migrations.AddField(
            model_name='movies',
            name='Movie_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
