# Generated by Django 5.0 on 2023-12-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0010_movies_movie_link_movies_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='Movie_link',
            new_name='Movie_file',
        ),
    ]
