# Generated by Django 4.2.2 on 2024-01-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0012_notification_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='Movie_cast',
        ),
    ]
