# Generated by Django 4.2.2 on 2024-01-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0013_remove_movies_movie_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='cast_img',
            field=models.ImageField(default='null.jpg', upload_to='cast'),
        ),
    ]
