# Generated by Django 4.2.2 on 2024-01-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0014_alter_cast_cast_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cast',
        ),
    ]
