# Generated by Django 4.2.2 on 2024-01-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0016_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.FloatField(),
        ),
    ]
