# Generated by Django 4.2.2 on 2024-01-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0017_notification_date_alter_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='updates',
            field=models.TextField(max_length=100),
        ),
    ]
