# Generated by Django 4.2.2 on 2024-01-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0018_alter_notification_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('validity', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=100)),
                ('availabilty', models.CharField(max_length=100)),
            ],
        ),
    ]
