# Generated by Django 5.0.1 on 2024-01-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0021_remove_payment_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
