# Generated by Django 5.0.1 on 2024-01-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0022_payment_expiry_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
