# Generated by Django 4.2.7 on 2024-01-10 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0024_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
