# Generated by Django 4.2.7 on 2024-01-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0026_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='plan_status',
            field=models.CharField(max_length=10),
        ),
    ]
